#! /bin/sh

# BSPWM Config - v2020-06-25
# 
# Maintainer:
#   Yves Hoppe <info@yveshoppe.de>
#

### DISPLAYS

xrandr --output DisplayPort-0 --mode 2560x1440 --rate 143.91
xrandr --output DisplayPort-1 --mode 2560x1440 --rate 143.91 --right-of DisplayPort-0
xrandr --output DisplayPort-2 --auto --orientation portrait --right-of DisplayPort-1

### AUTOSTART
killall "sxhkd"
sxhkd &
picom &
killall "polybar"
polybar bytee &

feh --bg-fill ~/wallpaper/forest-hut-purple.png
# variety &

nm-applet & 
numlockx on & 
dunst -config ~/.config/i3/config_dunst &
copyq &
xss-lock i3lock-fancy-rapid 3 5 & 
wmname LG3D 

### Workspace
bspc monitor DisplayPort-0 -d t1 dev1 dev2 dev3 dev4 vm1
bspc monitor DisplayPort-1 -d web web2 
bspc monitor DisplayPort-2 -d sp1 sp2

### Config
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          0
bspc config -m DisplayPort-1 top_padding 30

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### Coloring
bspc config normal_border_color "#000000"
bspc config focused_border_color "#87AFAF"
bspc config presel_feedback_color "#4C4C4C"

### Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating

# Partly floating if they have class (urxvt -name or xterm -class)
bspc rule -a my_float state=floating
bspc rule -a *:my_float state=floating

# Floating apps
bspc rule -a feh state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Arandr state=floating

